// ADD
export const ADD_MISSION = 'ADD_MISSION';
export const ADD_MISSION_SUCCESS = 'ADD_MISSION_SUCCESS';
export const ADD_MISSION_FAILED = 'ADD_MISSION_FAILED';

// UPDATE
export const UPDATE_MISSION = 'UPDATE_MISSION';
export const UPDATE_MISSION_SUCCESS = 'UPDATE_MISSION_SUCCESS';
export const UPDATE_MISSION_FAILED = 'UPDATE_MISSION_FAILED';

// DELETE
export const DELETE_MISSION = 'DELETE_MISSION';
export const DELETE_MISSION_SUCCESS = 'DELETE_MISSION_SUCCESS';
export const DELETE_MISSION_FAILED = 'DELETE_MISSION_FAILED';
